[package]
name = "sozu"
description = "sozu, a fast, reliable, hot reconfigurable HTTP reverse proxy"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu"
homepage = "http://sozu.io"
version = "0.11.48"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]
edition="2018"

include = [
  "README.md",
  "Cargo.toml",
  "src/**/*",
]

[[bin]]
name = "sozu"

[dependencies]
mio = { version = "^0.7", features = [ "os-poll", "uds" ] }
serde = "~1.0.2"
serde_json = "~1.0.1"
serde_derive = "~1.0.2"
nom = "^5.0"
nix  = "^0.17"
time = "^0.2"
slab = "^0.4.0"
libc = "^0.2"
rand = "^0.7"
tempfile = "^3.0"
futures = "^0.3"
lazy_static = "^1.1"
regex = "1.0"
jemallocator = {version = "^0.3", optional = true }
chrono = "0.4"
hex = "^0.4"
structopt = "^0.3"
structopt-derive = "^0.4"
prettytable-rs = { version = "^0.8", default-features = false}
smol = "0.2"
blocking = "0.4"
async-io = "0.1"
async-dup = "1.2"
futures-lite = "0.1"
log = "^0.4"

sozu-lib = { version = "^0.11", path = "../lib" }
sozu-command-lib = { version = "^0.11", path = "../command" }

[target.'cfg(target_os="linux")'.dependencies]
num_cpus = "^1.3.0"

[features]
default = [ "jemallocator" ]
unstable = []
logs-debug = ["sozu-lib/logs-debug", "sozu-command-lib/logs-debug"]
logs-trace = ["sozu-lib/logs-trace", "sozu-command-lib/logs-trace"]
use-openssl = ["sozu-lib/use-openssl"]
tolerant-http1-parser = ["sozu-lib/tolerant-http1-parser"]

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
